### ISSUE TITLE
which keeps crashing*

### ISSUE THREAD

**Issue by MarisaKirisame** [Akvelog/servcraft#1]

**Comment by Alpacius** [comment]
It keeps crashing now.

**Comment by MarisaKirisame** [comment]
I mean the grammar of the brief description is probably wrong

**Comment by YoukouTenhouin** [comment]
The description on Github is still the wrong version

**Comment by Alpacius** [comment]
@MarisaKirisame [here](https://github.com/Akvelog/servcraft/commit/07d002e586849e9fe8d0e8e16b545cc31bdd0a55)

**Comment by Alpacius** [comment]
@AbrahamHokuto Now it keeps crashing too.
